DATA CLEANING, EDA AND FEATURE ENGINEERING

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_excel('flight_price.xlsx')
df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [ ]:
#basic info about data
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [ ]:
#Feature Engineering - handle date of journey
df['date']=df['Date_of_Journey'].str.split('/').str[0]
df['month']=df['Date_of_Journey'].str.split('/').str[1]
df['year']=df['Date_of_Journey'].str.split('/').str[2]
df['Date']=df['date'].astype(int)
df['Month']=df['month'].astype(int)
df['Year']=df['month'].astype(int)

df.drop(['date','month','year'], axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int32
 12  Month            10683 non-null  int32
 13  Year             10683 non-null  int32
dtypes: int32(3), int64(1), object(10)
memory usage: 1.0+ MB

In [ ]:
#Handling Arrival Time - split by : into hour and minute
#First - we remove the date part from time wherever there
df['Arrival_Time']=df['Arrival_Time'].apply(lambda x:x.split(' ')[0])
df['Arrival_Hour']=df['Arrival_Time'].str.split(':').str[0]
df['Arrival_Minutes']=df['Arrival_Time'].str.split(':').str[1]
df.head(2)
df['Arrival_Hour']=df['Arrival_Hour'].astype(int)
df['Arrival_Minutes']=df['Arrival_Minutes'].astype(int)

In [ ]:
df['Dep_Hour']=df['Dep_Time'].str.split(':').str[0]
df['Dep_Min']=df['Dep_Time'].str.split(':').str[1]
df['Dep_Hour']=df['Dep_Hour'].astype(int)
df['Dep_Min']=df['Dep_Min'].astype(int)
df.drop('Dep_Time',axis=1,inplace=True)

In [ ]:
#Categorical features - Total stops
df['Total_Stops']=df['Total_Stops'].map({'non-stop':0, '1 stop':1, '2 stops':2, '3 stops':3, '4 stops':4, np.nan:1})

In [ ]:
df[df['Total_Stops'].isnull()]

Empty DataFrame
Columns: [Airline, Date_of_Journey, Source, Destination, Route, Arrival_Time, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Arrival_Hour, Arrival_Minutes, Dep_Hour, Dep_Min]
Index: []

In [ ]:
df.drop('Route', axis=1, inplace=True)

In [ ]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Hour,Dep_Min
0,IndiGo,24/03/2019,Banglore,New Delhi,01:10,2h 50m,0,No info,3897,24,3,3,1,10,22,20
1,Air India,1/05/2019,Kolkata,Banglore,13:15,7h 25m,2,No info,7662,1,5,5,13,15,5,50
2,Jet Airways,9/06/2019,Delhi,Cochin,04:25,19h,2,No info,13882,9,6,6,4,25,9,25
3,IndiGo,12/05/2019,Kolkata,Banglore,23:30,5h 25m,1,No info,6218,12,5,5,23,30,18,5
4,IndiGo,01/03/2019,Banglore,New Delhi,21:35,4h 45m,1,No info,13302,1,3,3,21,35,16,50

In [ ]:
#Get duration
df['Duration_Hour']=df['Duration'].str.split(' ').str[0].str.split('h').str[0]

In [ ]:
df['Duration_Min']=df['Duration'].str.split(' ').str[1].str.split('m').str[0]
df['Duration_Min']

0         50
1         25
2        NaN
3         25
4         45
        ...
10678     30
10679     35
10680    NaN
10681     40
10682     20
Name: Duration_Min, Length: 10683, dtype: object

In [ ]:
df['Duration_Min']=df['Duration_Min'].replace(np.nan,0)

In [ ]:
df['Duration_Hour']=df['Duration_Hour'].str.split('m').str[0]

In [ ]:
df['DurationInMin']=df['Duration_Hour'].astype(int)*60 + df['Duration_Min'].astype(int)

In [ ]:
df.drop('Duration', axis=1, inplace=True)

In [ ]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Arrival_Time,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Hour,Dep_Min,Duration_Hour,Duration_Min,DurationInMin
0,IndiGo,24/03/2019,Banglore,New Delhi,01:10,0,No info,3897,24,3,3,1,10,22,20,2,50,170
1,Air India,1/05/2019,Kolkata,Banglore,13:15,2,No info,7662,1,5,5,13,15,5,50,7,25,445
2,Jet Airways,9/06/2019,Delhi,Cochin,04:25,2,No info,13882,9,6,6,4,25,9,25,19,0,1140
3,IndiGo,12/05/2019,Kolkata,Banglore,23:30,1,No info,6218,12,5,5,23,30,18,5,5,25,325
4,IndiGo,01/03/2019,Banglore,New Delhi,21:35,1,No info,13302,1,3,3,21,35,16,50,4,45,285

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()

In [ ]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

encoder = OneHotEncoder()

ohe_cols=['Airline','Source', 'Destination', 'Additional_Info']
encoded=encoder.fit_transform(df[ohe_cols]).toarray()

encoded_df=pd.DataFrame(encoded, columns=encoder.get_feature_names_out(ohe_cols))

encoded_df.index=df.index
df=pd.concat([df.drop(ohe_cols, axis=1), encoded_df], axis=1)

In [ ]:
df.drop(['Date_of_Journey', 'Arrival_Time', 'Duration_Hour', 'Duration_Min'], axis=1, inplace=True)

In [ ]:
df.head()

,Total_Stops,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Hour,Dep_Min,DurationInMin,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0,3897,24,3,3,1,10,22,20,170,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2,7662,1,5,5,13,15,5,50,445,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2,13882,9,6,6,4,25,9,25,1140,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6218,12,5,5,23,30,18,5,325,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,13302,1,3,3,21,35,16,50,285,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

MODEL TRAINING AND TESTING - SPLITTING TESTING AND TRAINING DATA

In [ ]:
#Simple Linear Regression Model
from sklearn.model_selection import train_test_split
X=df.drop('Price', axis=1)
Y=df['Price']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
#Model training
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

lr=LinearRegression()
lr.fit(X_train, Y_train)

LinearRegression()

In [ ]:
#Model prediction and evaluation

Y_pred = lr.predict(X_test)

rmse=np.sqrt(mean_squared_error(Y_test, Y_pred))
r2=r2_score(Y_test, Y_pred)
print("Linear Regression RMSE: ", rmse)
print("Linear Regression R2 Score: ", r2)

Linear Regression RMSE:  2572.9688663442585
Linear Regression R2 Score:  0.6871962103057657

In [ ]:
#Ridge, Lasso Regression
from sklearn.linear_model import Ridge, Lasso
ridge=Ridge(alpha=1.0, random_state=42)
ridge.fit(X_train, Y_train)
Y_pred_ridge = ridge.predict(X_test)

lasso=Lasso(alpha=0.001, random_state=42)
lasso.fit(X_train,Y_train)
Y_pred_lasso = lasso.predict(X_test)

c:\Users\Sunishtha\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.110e+10, tolerance: 1.819e+07
  model = cd_fast.enet_coordinate_descent(

In [ ]:
rmse_ridge=np.sqrt(mean_squared_error(Y_test, Y_pred_ridge))
r2_ridge=r2_score(Y_test, Y_pred_ridge)
print("Ridge Regression RMSE: ", rmse_ridge)
print("Ridge Regression R2 Score: ", r2_ridge)

rmse_lasso=np.sqrt(mean_squared_error(Y_test, Y_pred_lasso))
r2_lasso=r2_score(Y_test, Y_pred_lasso)
print("Lasso Regression RMSE: ", rmse_lasso)
print("Lasso Regression R2 Score: ", r2_lasso)

Ridge Regression RMSE:  2556.696862983944
Ridge Regression R2 Score:  0.6911401751451215
Lasso Regression RMSE:  2572.9528401551092
Lasso Regression R2 Score:  0.6872001070004778

TREE MODELS - DECISION TREE & RANDOM FOREST

In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor(max_depth=10, min_samples_leaf=5, random_state=42)
dt.fit(X_train, Y_train)
Y_pred_dt = dt.predict(X_test)

rmse_dt=np.sqrt(mean_squared_error(Y_test, Y_pred_dt))
r2_dt=r2_score(Y_test, Y_pred_dt)
print("Decision Tree Regressor RMSE: ", rmse_dt)
print("Decision Tree Regressor R2 Score: ", r2_dt)

Decision Tree Regressor RMSE:  1925.4572734853152
Decision Tree Regressor R2 Score:  0.8248255689758819

In [ ]:
#Random Forest
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators=300, max_depth=20, min_samples_leaf=5, max_features='log2', random_state=42, n_jobs=-1)
rf.fit(X_train, Y_train)
Y_pred_rf = rf.predict(X_test)

rmse_rf=np.sqrt(mean_squared_error(Y_test, Y_pred_rf))
r2_rf=r2_score(Y_test, Y_pred_rf)
print("Random Forest Regressor RMSE: ", rmse_rf)
print("Random Forest Regressor R2 Score: ", r2_rf)

Random Forest Regressor RMSE:  1988.35634156156
Random Forest Regressor R2 Score:  0.8131937591174221

BOOSTING MODELS

In [ ]:
#Gradient Boosted Tree
from sklearn.ensemble import GradientBoostingRegressor
gbr=GradientBoostingRegressor(n_estimators=500, max_depth=5, learning_rate=0.1, max_features='sqrt', random_state=42, min_samples_leaf=5)
gbr.fit(X_train, Y_train)
Y_pred_gbr=gbr.predict(X_test)

rmse_gbr=np.sqrt(mean_squared_error(Y_test, Y_pred_gbr))
r2_gbr=r2_score(Y_test, Y_pred_gbr)
print("Gradient Boosting Regressor RMSE: ", rmse_gbr)
print("Gradient Boosting Regressor R2 Score: ", r2_gbr)

Gradient Boosting Regressor RMSE:  1431.1449317649826
Gradient Boosting Regressor R2 Score:  0.9032234407138968

In [ ]:
# Training performance
Y_train_pred = gbr.predict(X_train)

rmse_train = np.sqrt(mean_squared_error(Y_train, Y_train_pred))
r2_train = r2_score(Y_train, Y_train_pred)

print("Training RMSE:", rmse_train)
print("Training R²:", r2_train)

#Trainig & Test r2 scores are not too different so its not overfitting instead giving good results

Training RMSE: 1137.9869508495065
Training R²: 0.9391628458427528

In [ ]:
#XGBoost
from xgboost import XGBRegressor
xg=XGBRegressor(n_estimators=800,          # balanced number of trees
    learning_rate=0.05,        # conservative step
    max_depth=4,               # enough complexity
    subsample=0.8,             # randomness to prevent overfit
    colsample_bytree=0.8,      # feature sampling
    min_child_weight=3,        # avoid too small leaves
    reg_alpha=0.1,            # small L1
    reg_lambda=2.0,            # standard L2
    random_state=42,
    n_jobs=-1 )
xg.fit(X_train, Y_train)
Y_pred_xg=xg.predict(X_test)

rmse_xg=np.sqrt(mean_squared_error(Y_test, Y_pred_xg))
r2_xg=r2_score(Y_test, Y_pred_xg)
print("XG Boosting Regressor RMSE: ", rmse_xg)
print("XG Boosting Regressor R2 Score: ", r2_xg)

XG Boosting Regressor RMSE:  1556.4625949372594
XG Boosting Regressor R2 Score:  0.8855329751968384

In [ ]:
# Training performance for XGBoost
Y_train_pred_xg = xg.predict(X_train)

rmse_train_xg = np.sqrt(mean_squared_error(Y_train, Y_train_pred_xg))
r2_train_xg = r2_score(Y_train, Y_train_pred_xg)

print("Training RMSE:", rmse_train_xg)
print("Training R²:", r2_train_xg)

Training RMSE: 1307.4718747796235
Training R²: 0.9196919202804565

SAVE MODELS INTO PICKLE FILES

import pickle, os
os.makedirs("Models", exists=True)

pickle.dump(lr, open("models/linear_reg.pkl","wb"))
pickle.dump(ridge, open("models/ridge_reg.pkl","wb"))
pickle.dump(lasso, open("models/lasso_reg.pkl","wb"))
pickle.dump(dt, open("models/dt_reg.pkl","wb"))
pickle.dump(rf, open("models/rf_reg.pkl","wb"))
pickle.dump(gbr, open("models/gbr_reg.pkl","wb"))
pickle.dump(xg, open("models/xgb_reg.pkl","wb"))

pickle.dump(encoder, open("models/ohe_encoder.pkl","wb"))
pickle.dump(list(X.columns), open("models/feature_columns.pkl","wb"))

print("✅ All models + encoder + feature columns saved in models/ folder")